[workspace]
members=["crates/*", "reef_testing"]
default-members=[".", "crates/tinywasm", "crates/types", "crates/parser"]
resolver="2"

[profile.wasm]
opt-level="s"
lto="thin"
codegen-units=1
panic="abort"
inherits="release"

[workspace.package]
version="0.7.0"
edition="2021"
license="MIT OR Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/tinywasm"

[package]
name="tinywasm-root"
publish=false
edition="2021"

# [[bin]]
# name="wasm-rust"
# test=false

[[bin]]
name = "reef_testing"
path ="reef_testing"

[dev-dependencies]
color-eyre="0.6"
tinywasm={path="crates/tinywasm"}
wat={version="1"}
pretty_env_logger="0.5"

[profile.bench]
opt-level=3
lto="thin"
codegen-units=1
debug=true
