[package]
name = "wasm_test"
description = "Local testing"
edition = "2021"
version = "0.0.1"
authors = ["MikMuellerDev", "Konstantin Ebeling"]

[dependencies]
argh = { version = "0.1.12"}
color-eyre = { version = "0.6.3"}
log = { version = "0.4.21"}
tinywasm = { path = "../crates/tinywasm/" }
